# Generated by Django 4.2.14 on 2025-09-30 07:43

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Copon', models.CharField(max_length=10, unique=True, verbose_name='کد تخفیف')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2025, 9, 30, 7, 43, 32, 961638, tzinfo=datetime.timezone.utc), verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2025, 9, 30, 7, 43, 32, 961638, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان')),
                ('discount', models.IntegerField(verbose_name='درصد تخفیف')),
                ('isActive', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': 'کوپن تخفیفات',
            },
        ),
        migrations.CreateModel(
            name='Discount_basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_title', models.CharField(max_length=100, verbose_name='وضوع تخفیف')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2025, 9, 30, 7, 43, 32, 961638, tzinfo=datetime.timezone.utc), verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2025, 9, 30, 7, 43, 32, 961638, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('isActive', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': ' سبد تخفیف ',
                'verbose_name_plural': 'سبد تخفیف ها ',
            },
        ),
        migrations.CreateModel(
            name='Discount_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountBasket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_of_basket', to='discount.discount_basket', verbose_name='سبد تخفیف')),
            ],
            options={
                'verbose_name': 'جزییات سبد خرید',
                'verbose_name_plural': 'جزییات سبد تخفیف ها',
            },
        ),
    ]
