# Generated by Django 4.2.14 on 2025-10-02 11:38

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_cachedprice_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to),
        ),
    ]
