# Generated by Django 4.2.14 on 2025-10-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketassignment',
            name='is_read_user',
            field=models.BooleanField(default=True, verbose_name='خوانده شده توسط کاربر'),
        ),
    ]
