# Generated by Django 4.2.14 on 2025-10-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticketassignment_is_read_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketassignment',
            name='is_read_user',
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='is_read_user',
            field=models.BooleanField(default=True, verbose_name='خوانده شده توسط کاربر'),
        ),
    ]
