# Generated by Django 4.2.14 on 2025-10-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticketassignment_is_read_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='is_read_admin',
            field=models.BooleanField(default=True, verbose_name='خوانده شده توسط ادمی'),
        ),
    ]
