# Generated by Django 4.0.3 on 2025-09-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurity',
            name='isInfoFiled',
            field=models.BooleanField(default=False, verbose_name='وضعیت تکمیل اطلاعات'),
        ),
    ]
