# Generated by Django 4.0.3 on 2025-09-04 11:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('isActive', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='file.feature', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقادیر ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('isActive', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('isActive', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file.group', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'گروه محصول',
                'verbose_name_plural': 'گروه\u200cهای محصول',
            },
        ),
        migrations.CreateModel(
            name='FilesGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین')),
                ('image', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر')),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='file.file', verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'گالری فایل',
                'verbose_name_plural': 'گالری فایل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='FileFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='مقدار کالا')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.feature', verbose_name='ویژگی')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_value', to='file.file', verbose_name='فایل')),
                ('filterValue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file.featurevalue', verbose_name='مقدار برای فیلترینگ')),
            ],
            options={
                'verbose_name': 'ویژگی فایل',
                'verbose_name_plural': 'ویژگی\u200cهای فایل',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='features',
            field=models.ManyToManyField(through='file.FileFeature', to='file.feature', verbose_name='ویژگی\u200cها'),
        ),
        migrations.AddField(
            model_name='file',
            name='group',
            field=models.ManyToManyField(related_name='files_of_groups', to='file.group', verbose_name='دسته بندی کالا'),
        ),
        migrations.AddField(
            model_name='feature',
            name='group',
            field=models.ManyToManyField(related_name='features', to='file.group', verbose_name='گروه'),
        ),
    ]
