# Generated by Django 4.2.14 on 2025-09-30 07:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_suggest', models.BooleanField(default=False, verbose_name='پیشنهاد وضعیت')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('isActive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('isActive', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقادیر ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('isActive', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر')),
                ('downloadLink', models.URLField(blank=True, null=True, verbose_name='لینک دانلود خارجی')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا ها',
            },
        ),
        migrations.CreateModel(
            name='FileFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='مقدار کالا')),
            ],
            options={
                'verbose_name': 'ویژگی فایل',
                'verbose_name_plural': 'ویژگی\u200cهای فایل',
            },
        ),
        migrations.CreateModel(
            name='FilesGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین')),
                ('image', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'گالری فایل',
                'verbose_name_plural': 'گالری فایل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('isActive', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'گروه محصول',
                'verbose_name_plural': 'گروه\u200cهای محصول',
            },
        ),
        migrations.CreateModel(
            name='Like_or_unLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('like', models.BooleanField(default=False)),
                ('unlike', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_request', to='file.comment', verbose_name='نظر')),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_request', to='file.file')),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک ها',
            },
        ),
    ]
