# Generated by Django 4.2.14 on 2025-09-30 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_or_unlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL, verbose_name='پیشنهادات کاربر'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='file.group', verbose_name='والد'),
        ),
        migrations.AddField(
            model_name='filesgallery',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='file.file', verbose_name='فایل'),
        ),
        migrations.AddField(
            model_name='filefeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.feature', verbose_name='ویژگی'),
        ),
        migrations.AddField(
            model_name='filefeature',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_value', to='file.file', verbose_name='فایل'),
        ),
        migrations.AddField(
            model_name='filefeature',
            name='filterValue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file.featurevalue', verbose_name='مقدار برای فیلترینگ'),
        ),
        migrations.AddField(
            model_name='file',
            name='features',
            field=models.ManyToManyField(through='file.FileFeature', to='file.feature', verbose_name='ویژگی\u200cها'),
        ),
        migrations.AddField(
            model_name='file',
            name='group',
            field=models.ManyToManyField(related_name='files_of_groups', to='file.group', verbose_name='دسته بندی کالا'),
        ),
        migrations.AddField(
            model_name='featurevalue',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='file.feature', verbose_name='ویژگی'),
        ),
        migrations.AddField(
            model_name='feature',
            name='group',
            field=models.ManyToManyField(related_name='features', to='file.group', verbose_name='گروه'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='file.comment', verbose_name='کامنت'),
        ),
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_product', to='file.file'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_approving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apporiv_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
