# Generated by Django 4.0.3 on 2025-09-05 18:23

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file_image_alter_filesgallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='filesgallery',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
    ]
