# Generated by Django 4.2.14 on 2025-09-07 15:00

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_comment_is_suggest_alter_file_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='downloadLink',
            field=models.URLField(blank=True, null=True, verbose_name='لینک دانلود خارجی'),
        ),
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='filesgallery',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
    ]
