# Generated by Django 4.2.14 on 2025-09-10 14:43

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_rename_is_active_comment_isactive_alter_file_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'کالا', 'verbose_name_plural': 'کالا ها'},
        ),
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='filesgallery',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
    ]
