# Generated by Django 4.2.14 on 2025-09-16 09:49

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_file_download_file_alter_file_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='download_file',
        ),
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='filesgallery',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
    ]
