# Generated by Django 4.2.14 on 2025-09-10 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0007_rename_is_active_comment_isactive_alter_file_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isActive', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.base')),
                ('isFinally', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('orderCode', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد سفارش')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف روی فاکتور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('confirmed', 'تأیید شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('on_hold', 'در انتظار بررسی')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
            bases=('order.base',),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت کالا در فاکتور')),
                ('detail_of_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='جزییات سفارش')),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_details_file', to='file.file', verbose_name='محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_details', to='order.order', verbose_name='سفارش')),
            ],
        ),
    ]
