# Generated by Django 4.2.14 on 2025-09-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='detail_of_order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='qty',
        ),
    ]
