# Generated by Django 4.2.14 on 2025-09-16 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_alter_file_image_alter_filesgallery_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_rename_customer_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='file.file', verbose_name='فایل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cها',
                'unique_together': {('user', 'file')},
            },
        ),
    ]
