# Generated by Django 4.2.14 on 2025-09-30 07:43

import apps.main.models
from django.db import migrations, models
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_banner', models.CharField(max_length=100, verbose_name='نام بنر')),
                ('text_banner', models.CharField(max_length=300, verbose_name='متن بنر')),
                ('alt_slide', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوشتار عکس')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to)),
                ('is_active', models.BooleanField(default=False)),
                ('register_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('End_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان')),
            ],
        ),
        migrations.CreateModel(
            name='InfoCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='نام شماره')),
                ('mobile_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن همراه')),
                ('logo_name', models.FileField(upload_to=utils.FileUpload.upload_to, validators=[apps.main.models.validate_image_or_svg])),
                ('register_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
            ],
            options={
                'verbose_name': 'اطلاعات شرکت',
                'verbose_name_plural': 'اطلاعات های شرکت',
            },
        ),
        migrations.CreateModel(
            name='MetaTagMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_header', models.CharField(max_length=100, verbose_name='عنوان صفحه')),
                ('title_og', models.CharField(max_length=100, verbose_name='عنوان صفحه og')),
                ('description', models.TextField(verbose_name='توضیحات صفحه')),
                ('keywordf', models.CharField(max_length=100, verbose_name='لیست کلمات کلیدی')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ساخته شده در تاریخ')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
            ],
            options={
                'verbose_name': 'متا تگ',
                'verbose_name_plural': 'متا تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Slider_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_slider', models.CharField(max_length=100, verbose_name='متن اسلایدر')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر')),
                ('alt_slide', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوشتار عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('register_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('End_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'اسلایدر مرکز',
                'verbose_name_plural': 'اسلایدرها مرکز ها',
            },
        ),
        migrations.CreateModel(
            name='Slider_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_slider', models.CharField(max_length=100, verbose_name='متن اسلایدر')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر')),
                ('alt_slide', models.CharField(max_length=100, verbose_name='نوشتار عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('register_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('End_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
    ]
