# Generated by Django 4.2.14 on 2025-10-02 17:17

import apps.main.models
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_banner_image_name_alter_infocompany_logo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='infocompany',
            name='logo_name',
            field=models.FileField(upload_to=utils.FileUpload.upload_to, validators=[apps.main.models.validate_image_or_svg]),
        ),
        migrations.AlterField(
            model_name='slider_main',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slider_site',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
    ]
